### ISSUE TITLE
Travis install

### ISSUE THREAD

**Issue by MichaelClerx** [SABS-R3-projects/PKPD#4]
Hi guys!

Few quick comments after looking at your travis config

1. There's a lot of PINTS constants that you don't need (these lines can all go, I think)
2. You have a very big `requirements.txt` file with "pinned" (version-specific) dependencies, not sure you need this!
3. PINTS isn't pip installable yet, so you'll need to do something more complicated, e.g. adding this to your travis `before_install` bit: ```- pip install -e git://github.com/pints-team/pints.git#egg=pints```
4. There's no `setup.py` file, so `pip install .` won't do anything

**Comment by simonmarchant** [comment]
Thanks @MichaelClerx , we think we have it working now and this was useful, so thankyou!
